// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Category struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	ImageUrl    string    `json:"image_url"`
	CreatedAt   time.Time `json:"created_at"`
}

type Characteristic struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type City struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Image struct {
	ID        int64     `json:"id"`
	ProductID int64     `json:"product_id"`
	AltText   string    `json:"alt_text"`
	ImageUrl  string    `json:"image_url"`
	CreatedAt time.Time `json:"created_at"`
}

type Policy struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Product struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CategoryID  int64     `json:"category_id"`
	CityID      int64     `json:"city_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type ProductCharacteristic struct {
	ProductID        int64 `json:"product_id"`
	CharacteristicID int64 `json:"characteristic_id"`
}

type ProductPolicy struct {
	ProductID int64 `json:"product_id"`
	PolicyID  int64 `json:"policy_id"`
}
