openapi: 3.0.1
info:
  title: Proyecto Integrador
  description: Un remake del proyecto integrador con Golang
  version: 1.0.0
servers:
- url: https://example.com
paths:
  /category:
    get:
      summary: Returns a list of all product categories
      tags:
        - category
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  type: array
                  items:
                    type: object
                    $ref: '#/components/schemas/CategoryResponse'
    post:
      summary: Create a product category
      tags:
        - category
      requestBody:
        description: Category to be added 
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/CategoryRequest'
      responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                    type: object
                    $ref: '#/components/schemas/CategoryResponse'
  /category/{id}:
    get:
      summary: Get category with specific id
      tags:
        - category
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The category ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  type: object
                  $ref: '#/components/schemas/CategoryResponse'
    patch:
      summary: Patch category with specific id
      tags:
        - category
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The category ID
      requestBody:
        description: category to be updated
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/CategoryRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  type: object
                  $ref: '#/components/schemas/CategoryResponse'
    delete:
      summary: Delete category with specific id
      tags:
        - category
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The category ID
      responses:
        '204':
          description: Category with given id deleted
          content: {}
components:
  schemas:
    CategoryRequest:
      type: object
      properties:
        title:
          type: string
          example: SUV car
        description:
          type: string
          example: car to take you on the road
        image_url:
          type: string
    CategoryResponse:
      type: object
      properties:
        id:
          type: integer
          example: 10
        title:
          type: string
          example: SUV car
        description:
          type: string
          example: car to take you on the road
        image_url:
          type: string
        created_at:
          type: string
          format: date-time
tags:
  - name: category
    description: product category